### PR TITLE
added contribute

### PR DESCRIPTION
**Pull request by CodeAjay**
Added the contribute link to the bottom of the timer

### CODE REVIEW

**Comment by rajbos** [comment]
Nice work!

Can you try to get the link beneath the GitHub logo so it is less intrusive? 

image

I'd also like to make it look more like the GitHub contribution button that I also use on my [blog](https://github.com/rajbos/rajbos.github.io/blob/3523a450712392021d9820f25a626bcd8ad18e45/_layouts/post.html#L41):
image

**Comment by CodeAjay** [comment]
Can you clear that what you really want to Contribute to the project with the GitHub logo below or make a contribution button like on your blog page?

**Comment by rajbos** [comment]
I would like the "Contribute to project" button to be **beneath** the image, **and** use the image and border like on my blog 🙌 .

**Comment by CodeAjay** [comment]
Added image and contribute button.

**Comment by rajbos** [comment]
Thanks! Looks good. I'll merge it in and remove the big logo from the background image, so it does not show up twice 👍 .

**Pull request merged**
